/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTableQrsRouteImport } from './routes/admin.table-qrs'
import { Route as AdminFloorPlanRouteImport } from './routes/admin.floor-plan'

const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTableQrsRoute = AdminTableQrsRouteImport.update({
  id: '/table-qrs',
  path: '/table-qrs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFloorPlanRoute = AdminFloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/waiter': typeof WaiterRoute
  '/admin/floor-plan': typeof AdminFloorPlanRoute
  '/admin/table-qrs': typeof AdminTableQrsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/waiter': typeof WaiterRoute
  '/admin/floor-plan': typeof AdminFloorPlanRoute
  '/admin/table-qrs': typeof AdminTableQrsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cashier': typeof CashierRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/waiter': typeof WaiterRoute
  '/admin/floor-plan': typeof AdminFloorPlanRoute
  '/admin/table-qrs': typeof AdminTableQrsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cashier'
    | '/kitchen'
    | '/login'
    | '/order'
    | '/waiter'
    | '/admin/floor-plan'
    | '/admin/table-qrs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cashier'
    | '/kitchen'
    | '/login'
    | '/order'
    | '/waiter'
    | '/admin/floor-plan'
    | '/admin/table-qrs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cashier'
    | '/kitchen'
    | '/login'
    | '/order'
    | '/waiter'
    | '/admin/floor-plan'
    | '/admin/table-qrs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CashierRoute: typeof CashierRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  WaiterRoute: typeof WaiterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/table-qrs': {
      id: '/admin/table-qrs'
      path: '/table-qrs'
      fullPath: '/admin/table-qrs'
      preLoaderRoute: typeof AdminTableQrsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/floor-plan': {
      id: '/admin/floor-plan'
      path: '/floor-plan'
      fullPath: '/admin/floor-plan'
      preLoaderRoute: typeof AdminFloorPlanRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFloorPlanRoute: typeof AdminFloorPlanRoute
  AdminTableQrsRoute: typeof AdminTableQrsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFloorPlanRoute: AdminFloorPlanRoute,
  AdminTableQrsRoute: AdminTableQrsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CashierRoute: CashierRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  WaiterRoute: WaiterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
